In [1]:
import pandas as pd
import math

In [2]:
park_factor_df = pd.read_csv("park_factor_stats.csv")
display(park_factor_df)

,year,team_id,team,runs at home for,hr at home for,runs on road for,hr on road for,runs at home against,hr at home against,runs on road against,hr on road against,park id
0,2002,team-10-3,Anaheim,404,71,447,81,318,70,326,99,1.0
1,2003,team-10-3,Anaheim,352,68,384,82,339,84,404,106,1.0
2,2004,team-10-3,Anaheim,391,77,445,85,383,94,351,76,1.0
3,2005,team-10-3,Anaheim,361,71,400,76,311,74,332,84,1.0
4,2006,team-10-3,Anaheim,366,69,400,90,346,72,386,86,1.0
5,2007,team-10-3,Anaheim,460,61,362,62,348,68,383,83,1.0
6,2008,team-10-3,Anaheim,383,72,382,87,354,82,343,78,1.0
7,2009,team-10-3,Anaheim,444,90,439,83,386,104,375,76,1.0
8,2010,team-10-3,Anaheim,319,69,362,86,322,68,380,80,1.0
9,2011,team-10-3,Anaheim,305,62,362,93,287,69,346,73,1.0
10,2012,team-10-3,Anaheim,348,82,419,105,309,79,390,107,1.0
11,2013,team-10-3,Anaheim,352,77,381,87,371,80,366,87,1.0
12,2014,team-10-3,Anaheim,362,73,411,82,310,55,320,71,1.0
13,2015,team-10-3,Anaheim,320,94,341,82,298,70,377,96,1.0
14,2016,team-10-3,Anaheim,337,81,380,75,351,106,376,102,1.0
15,2017,team-10-3,Anaheim,356,97,354,89,335,105,374,119,1.0
16,2018,team-10-3,Anaheim,355,114,366,100,355,109,367,96,1.0
17,2002,team-10-29,Arizona,454,83,365,82,350,84,324,86,2.0
18,2003,team-10-29,Arizona,398,79,319,73,371,83,314,67,2.0
19,2004,team-10-29,Arizona,337,78,278,57,445,109,454,88,2.0
20,2005,team-10-29,Arizona,335,97,361,94,473,100,383,93,2.0
21,2006,team-10-29,Arizona,403,86,370,74,429,102,359,66,2.0
22,2007,team-10-29,Arizona,386,91,326,80,374,88,358,81,2.0
23,2008,team-10-29,Arizona,392,77,328,82,366,81,340,66,2.0
24,2009,team-10-29,Arizona,386,87,334,86,431,87,351,81,2.0
25,2010,team-10-29,Arizona,384,98,329,82,409,103,427,107,2.0
26,2011,team-10-29,Arizona,400,93,331,79,344,80,318,79,2.0
27,2012,team-10-29,Arizona,391,84,343,81,376,90,312,65,2.0
28,2013,team-10-29,Arizona,343,68,342,62,338,81,357,95,2.0
29,2014,team-10-29,Arizona,344,62,271,56,383,86,359,68,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
480,2006,team-10-14,Toronto,449,121,360,78,358,94,396,91,29.0
481,2007,team-10-14,Toronto,380,90,373,75,325,83,374,74,29.0
482,2008,team-10-14,Toronto,359,69,355,57,289,56,321,78,29.0
483,2009,team-10-14,Toronto,389,104,409,105,370,90,401,91,29.0
484,2010,team-10-14,Toronto,387,146,368,111,348,81,380,69,29.0
485,2011,team-10-14,Toronto,387,103,356,83,418,95,343,84,29.0
486,2012,team-10-14,Toronto,368,102,348,96,385,102,399,102,29.0
487,2013,team-10-14,Toronto,380,95,332,90,395,119,361,76,29.0
488,2014,team-10-14,Toronto,387,98,336,79,332,88,354,63,29.0
489,2015,team-10-14,Toronto,450,123,441,109,292,80,378,93,29.0
490,2016,team-10-14,Toronto,401,107,358,114,363,96,303,87,29.0
491,2017,team-10-14,Toronto,332,105,361,117,386,99,398,104,29.0
492,2018,team-10-14,Toronto,361,115,348,102,393,110,439,98,29.0
493,2002,team-10-20,Washington,394,85,341,77,338,78,380,87,30.0
494,2003,team-10-20,Washington,436,81,275,63,392,116,324,65,30.1
495,2004,team-10-20,Washington,290,69,345,82,366,86,403,105,30.1
496,2005,team-10-20,Washington,289,46,350,71,320,66,353,74,30.2
497,2006,team-10-20,Washington,373,74,373,90,412,91,460,102,30.2
498,2007,team-10-20,Washington,324,48,349,75,355,77,428,110,30.2
499,2008,team-10-20,Washington,316,51,325,66,426,97,399,93,30.3
500,2009,team-10-20,Washington,369,76,341,80,426,86,448,87,30.3
501,2010,team-10-20,Washington,327,74,328,75,359,76,383,75,30.3
502,2011,team-10-20,Washington,311,83,313,71,304,65,339,64,30.3
503,2012,team-10-20,Washington,367,101,364,93,303,64,291,65,30.3
504,2013,team-10-20,Washington,349,70,307,91,296,65,330,77,30.3
505,2014,team-10-20,Washington,362,63,324,89,279,45,276,65,30.3
506,2015,team-10-20,Washington,360,91,343,86,309,72,326,73,30.3
507,2016,team-10-20,Washington,365,102,398,101,307,79,305,76,30.3
508,2017,team-10-20,Washington,421,107,398,108,345,99,327,90,30.3
509,2018,team-10-20,Washington,409,96,362,95,363,114,319,84,30.3

In [6]:
# since we built this dataframe file, we know that all data is present.  any field could be counted
df_length = park_factor_df.year.count() - 1

# N = Number of teams in League
# With the number of interleague games being played, we will regard "league" as the Major Leagues
# we know this to be constant through the period in scope
N = 30;

In [3]:
# total runs and homeruns for league will be needed
park_factor_groupby_year = park_factor_df.groupby('year')
league_runs = park_factor_groupby_year["runs at home for"].sum() + park_factor_groupby_year["runs at home against"].sum()
league_runs_df = pd.DataFrame(league_runs)

league_hrs  = park_factor_groupby_year["hr at home for"].sum() + park_factor_groupby_year["hr at home against"].sum()
league_hrs_df = pd.DataFrame(league_hrs)

display(league_runs_df)
runs_league = league_runs.loc[2006]
runs_league

          0
year
2002  22408
2003  22978
2004  23376
2005  22325
2006  23599
2007  23322
2008  22585
2009  22419
2010  21308
2011  20808
2012  21017
2013  20255
2014  19761
2015  20647
2016  21744
2017  22582
2018  21630

23599

Compute the park factors for all teams / all years

In [18]:
year_list = []
team_list = []
PRFa_list = []
PHRFa_list = []
PNHRFa_list = []

for i in range(2,df_length):
# for i in range(509,510):    # for testing
    year = park_factor_df.iloc[i, 0]
    team = park_factor_df.iloc[i, 2]
    curr_park = park_factor_df.iloc[i, 11]
    
    tot_weight = 4
    tot_r_home  = (park_factor_df.iloc[i, 3] + park_factor_df.iloc[i, 7])*4
    tot_hr_home = (park_factor_df.iloc[i, 4] + park_factor_df.iloc[i, 8])*4
    tot_r_road  = (park_factor_df.iloc[i, 5] + park_factor_df.iloc[i, 9])*4
    tot_hr_road = (park_factor_df.iloc[i, 6] + park_factor_df.iloc[i, 10])*4
        
    j = i - 2
    if (park_factor_df.iloc[j, 11] == curr_park):
        tot_weight  += 1
        tot_r_home  += (park_factor_df.iloc[j, 3] + park_factor_df.iloc[j, 7])
        tot_hr_home += (park_factor_df.iloc[j, 4] + park_factor_df.iloc[j, 8])
        tot_r_road  += (park_factor_df.iloc[j, 5] + park_factor_df.iloc[j, 9])
        tot_hr_road += (park_factor_df.iloc[j, 6] + park_factor_df.iloc[j, 10])

    j = i - 1
    if (park_factor_df.iloc[j, 11] == curr_park):
        tot_weight  += 1
        tot_r_home  += (park_factor_df.iloc[j, 3] + park_factor_df.iloc[j, 7])
        tot_hr_home += (park_factor_df.iloc[j, 4] + park_factor_df.iloc[j, 8])
        tot_r_road  += (park_factor_df.iloc[j, 5] + park_factor_df.iloc[j, 9])
        tot_hr_road += (park_factor_df.iloc[j, 6] + park_factor_df.iloc[j, 10])
      
    j = i + 1
    if (j <= df_length):    # don't go past end of data
        if (park_factor_df.iloc[j, 11] == curr_park):
            tot_weight  += 1
            tot_r_home  += (park_factor_df.iloc[j, 3] + park_factor_df.iloc[j, 7])
            tot_hr_home += (park_factor_df.iloc[j, 4] + park_factor_df.iloc[j, 8])
            tot_r_road  += (park_factor_df.iloc[j, 5] + park_factor_df.iloc[j, 9])
            tot_hr_road += (park_factor_df.iloc[j, 6] + park_factor_df.iloc[j, 10])
              
    j = i + 2
    if (j <= df_length):    # don't go past end of data
        if (park_factor_df.iloc[j, 11] == curr_park):
            tot_weight  += 1
            tot_r_home  += (park_factor_df.iloc[j, 3] + park_factor_df.iloc[j, 7])
            tot_hr_home += (park_factor_df.iloc[j, 4] + park_factor_df.iloc[j, 8])
            tot_r_road  += (park_factor_df.iloc[j, 5] + park_factor_df.iloc[j, 9])
            tot_hr_road += (park_factor_df.iloc[j, 6] + park_factor_df.iloc[j, 10])
            
    PRF  = (tot_r_home  / tot_weight) / (tot_r_road  / tot_weight)
    PRFa = (( N - 1) * PRF + ( N - PRF)) / (2 * (N - 1))
    PHRF = (tot_hr_home / tot_weight) / (tot_hr_road / tot_weight)
    PHRFa = (( N - 1) * PHRF + ( N - PHRF)) / (2 * (N - 1))
    

    runs_league = league_runs.loc[year]
    hr_league   = league_hrs.loc[year]
    factor_a    = 1.5 * (hr_league/runs_league)
    factor_b    = 1 - factor_a
    PNHRFa      = math.sqrt((PRFa - (factor_a * PHRFa)) / factor_b)
    
    year_list.append(year)
    team_list.append(team)
    PRFa_list.append(PRFa)
    PHRFa_list.append(PHRFa)
    PNHRFa_list.append(PNHRFa)
    
# with that done, assemble our park factor df
dict1 = {"year" : year_list,
         "team" : team_list,
         "PRFa" : PRFa_list,
         "PHRFa" : PHRFa_list,
         "PNHRFa" : PNHRFa_list}
pf_data_df = pd.DataFrame(dict1)

In [19]:
display(pf_data_df)

     year        team      PRFa     PHRFa    PNHRFa
0    2004     Anaheim  0.971480  0.969559  0.986161
1    2005     Anaheim  0.970442  0.949513  0.990497
2    2006     Anaheim  0.976184  0.937802  0.998080
3    2007     Anaheim  1.011675  0.964961  1.016631
4    2008     Anaheim  0.996130  0.967101  1.005008
5    2009     Anaheim  0.993903  1.018510  0.990644
6    2010     Anaheim  0.948390  0.937093  0.976639
7    2011     Anaheim  0.941117  0.929078  0.973138
8    2012     Anaheim  0.928886  0.900693  0.971705
9    2013     Anaheim  0.957594  0.933685  0.984986
10   2014     Anaheim  0.952973  0.938629  0.979619
11   2015     Anaheim  0.951343  0.968133  0.970586
12   2016     Anaheim  0.960055  1.007360  0.964463
13   2017     Anaheim  0.968030  0.999651  0.972862
14   2018     Anaheim  0.978464  1.046252  0.967270
15   2002     Arizona  1.075676  1.030267  1.048298
16   2003     Arizona  1.079449  1.063305  1.042958
17   2004     Arizona  1.052131  1.098141  1.013597
18   2005     Arizona  1.052102  1.061521  1.023383
19   2006     Arizona  1.058160  1.109334  1.015638
20   2007     Arizona  1.060150  1.055183  1.030764
21   2008     Arizona  1.061852  1.048315  1.033605
22   2009     Arizona  1.072541  1.030264  1.045975
23   2010     Arizona  1.049032  1.037918  1.026829
24   2011     Arizona  1.057580  1.037020  1.033258
25   2012     Arizona  1.059421  1.061739  1.028669
26   2013     Arizona  1.024472  1.003512  1.017605
27   2014     Arizona  1.062858  1.058720  1.031884
28   2015     Arizona  1.048320  1.000357  1.036777
29   2016     Arizona  1.084213  1.082256  1.041849
..    ...         ...       ...       ...       ...
477  2005     Toronto  1.025096  1.105952  0.991958
478  2006     Toronto  1.021627  1.098090  0.990870
479  2007     Toronto  0.986383  1.065122  0.974438
480  2008     Toronto  0.986015  1.029341  0.982473
481  2009     Toronto  0.985699  1.028658  0.981748
482  2010     Toronto  0.998452  1.072618  0.981216
483  2011     Toronto  1.037328  1.076460  1.009066
484  2012     Toronto  1.018919  1.064724  0.997006
485  2013     Toronto  1.033044  1.096341  0.999839
486  2014     Toronto  1.019548  1.084257  0.994692
487  2015     Toronto  0.989279  1.025425  0.984501
488  2016     Toronto  1.024566  1.018769  1.014015
489  2017     Toronto  0.984433  0.987014  0.991298
490  2018     Toronto  0.992602  1.033580  0.983208
491  2002  Washington  1.007365  0.997056  1.006302
492  2003  Washington  1.126525  1.168517  1.051143
493  2004  Washington  0.981313  0.967485  0.994360
494  2005  Washington  0.943012  0.889525  0.984992
495  2006  Washington  0.961476  0.911626  0.993693
496  2007  Washington  0.944489  0.865527  0.990680
497  2008  Washington  1.005820  0.975178  1.010201
498  2009  Washington  0.998158  0.992186  1.000599
499  2010  Washington  0.991647  1.001584  0.993413
500  2011  Washington  0.987126  1.008570  0.988258
501  2012  Washington  1.004347  0.985194  1.007352
502  2013  Washington  1.004805  0.941827  1.018824
503  2014  Washington  1.014872  0.923695  1.028268
504  2015  Washington  1.005333  0.981530  1.009221
505  2016  Washington  1.004311  1.004489  1.002097
506  2017  Washington  1.021833  1.026225  1.009374

[507 rows x 5 columns]

In [20]:
pf_data_df.to_csv("parkFactor.csv", index=False, header=True)